import json
import time
import sys
import os

import psycopg2
import requests as _requests

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from context import get_db

TOOL_DEFINITIONS = [
    {
        "name": "query_problems",
        "description": "Query active or resolved Problems from Jarvis. Problems group related alerts for the same host.",
        "input_schema": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "enum": ["open", "resolved", "all"],
                    "description": "Filter by status. Default: all"
                },
                "host": {
                    "type": "string",
                    "description": "Filter by host key (partial match, optional)"
                },
                "limit": {"type": "integer", "description": "Max results. Default: 10"}
            }
        }
    },
    {
        "name": "query_events",
        "description": "Query infrastructure events: anomalies, state changes, threshold violations.",
        "input_schema": {
            "type": "object",
            "properties": {
                "host":          {"type": "string",  "description": "Filter by host (optional)"},
                "event_type":    {"type": "string",  "description": "e.g. cpu_percent_anomaly, service_stopped"},
                "severity":      {"type": "string",  "enum": ["critical","high","medium","low"]},
                "since_minutes": {"type": "integer", "description": "Look back N minutes. Default: 60"},
                "limit":         {"type": "integer", "description": "Max results. Default: 20"}
            }
        }
    },
    {
        "name": "query_agents",
        "description": "List all monitored agents/hosts with last seen time.",
        "input_schema": {
            "type": "object",
            "properties": {
                "active_only": {
                    "type": "boolean",
                    "description": "If true, only agents seen in last 5 minutes"
                }
            }
        }
    },
    {
        "name": "query_metrics",
        "description": "Get historical CPU, memory, disk metrics for a specific host.",
        "input_schema": {
            "type": "object",
            "properties": {
                "host":          {"type": "string",  "description": "Host key (partial match)"},
                "since_minutes": {"type": "integer", "description": "Look back N minutes. Default: 60"}
            },
            "required": ["host"]
        }
    },
    {
        "name": "query_alerts",
        "description": "Query recent alerts generated by Jarvis.",
        "input_schema": {
            "type": "object",
            "properties": {
                "host":          {"type": "string"},
                "severity":      {"type": "string", "enum": ["critical","high","medium","low"]},
                "since_minutes": {"type": "integer", "description": "Default: 60"},
                "limit":         {"type": "integer", "description": "Default: 20"}
            }
        }
    },
    {
        "name": "get_config",
        "description": "Get current Jarvis configuration values.",
        "input_schema": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "description": "Filter by category: thresholds, llm, baseline, retention, problems, agent"
                }
            }
        }
    },
    {
        "name": "query_instrumentation_coverage",
        "description": "Shows which processes on a host are producing OTel traces (instrumented) vs running without observability.",
        "input_schema": {
            "type": "object",
            "properties": {
                "host":          {"type": "string",  "description": "Host key (partial match)"},
                "since_minutes": {"type": "integer", "description": "Look back N minutes for traces. Default: 30"}
            },
            "required": ["host"]
        }
    },
    {
        "name": "query_instrumentation_recommendations",
        "description": "Lists AI-generated instrumentation recommendations (pending, applied, skipped) for a host.",
        "input_schema": {
            "type": "object",
            "properties": {
                "host":   {"type": "string", "description": "Host key (partial match, optional)"},
                "status": {"type": "string", "enum": ["pending", "applied", "skipped", "all"],
                           "description": "Filter by status. Default: all"}
            }
        }
    },
    {
        "name": "request_instrumentation",
        "description": "Creates an AI instrumentation recommendation for a specific process on a host. Use this when you identify a process that needs OTel tracing.",
        "input_schema": {
            "type": "object",
            "properties": {
                "host":         {"type": "string",  "description": "Full host key"},
                "process_name": {"type": "string",  "description": "Process name to instrument"},
                "pid":          {"type": "integer", "description": "Process PID (optional)"},
                "technology":   {"type": "string",  "enum": ["python","nodejs","java","dotnet"],
                                 "description": "Runtime technology"},
                "priority":     {"type": "string",  "enum": ["urgent","normal"], "description": "Default: normal"},
                "reason":       {"type": "string",  "description": "Why this process needs instrumentation"}
            },
            "required": ["host", "process_name", "reason"]
        }
    },
    {
        "name": "agentless_run",
        "description": (
            "Execute a PowerShell script on any remote Windows machine via WinRM. "
            "Use this for live investigation AND remediation — exactly like a shell. "
            "Examples: get real-time process list, read log files, check service state, restart services, "
            "edit config files, create scheduled tasks, run diagnostics, apply fixes. "
            "Works for both investigation (read-only) and remediation scripts."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "machine": {
                    "type": "string",
                    "description": "Target machine hostname (e.g. WKS-DESKTOP01, SRV-APP02)"
                },
                "script": {
                    "type": "string",
                    "description": "PowerShell script to execute on the remote machine"
                },
                "machine_type": {
                    "type": "string",
                    "enum": ["workstation", "server"],
                    "description": "workstation (Kerberos gMSA) or server (NTLM). Default: workstation"
                },
                "timeout_s": {
                    "type": "integer",
                    "description": "Execution timeout in seconds (default 60, max 120)"
                }
            },
            "required": ["machine", "script"]
        }
    },
    {
        "name": "manage_webhook",
        "description": (
            "Manage Solution Driver notification webhooks. "
            "Jarvis sends rich JSON alerts to these URLs when a significant problem is detected. "
            "The webhook receives the problem, machine state, AI investigation, and a callback_url "
            "so the analyst can reply and converse with Jarvis. "
            "Use action='list' to see current webhooks, 'add' to register a new one, "
            "'disable'/'enable' to toggle, 'remove' to delete."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": ["list", "add", "enable", "disable", "remove"],
                    "description": "Action to perform"
                },
                "url": {
                    "type": "string",
                    "description": "Webhook URL (required for add/enable/disable/remove)"
                },
                "name": {
                    "type": "string",
                    "description": "Friendly name for the webhook (optional for add)"
                },
                "min_severity": {
                    "type": "string",
                    "enum": ["low", "medium", "high", "critical"],
                    "description": "Minimum severity to notify. Default: high"
                },
                "host_filter": {
                    "type": "string",
                    "description": "Comma-separated hostname prefixes to filter (empty = all hosts)"
                }
            },
            "required": ["action"]
        }
    },
    {
        "name": "list_conversations",
        "description": (
            "List active Solution Driver conversations between Jarvis and analysts. "
            "Each conversation starts when Jarvis detects a significant problem and notifies webhooks. "
            "Shows status, problem, host, and last activity."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "enum": ["awaiting_analyst", "in_progress", "action_approved",
                             "action_rejected", "resolved", "expired", "all"],
                    "description": "Filter by status. Default: all active"
                },
                "host": {
                    "type": "string",
                    "description": "Filter by host (partial match, optional)"
                },
                "limit": {"type": "integer", "description": "Max results. Default: 10"}
            }
        }
    },
    {
        "name": "get_conversation",
        "description": (
            "Get the full message history of a Solution Driver conversation. "
            "Shows all exchanges between the analyst and Jarvis, including proposed actions and outcomes."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "type": "string",
                    "description": "Conversation UUID (from list_conversations)"
                }
            },
            "required": ["conversation_id"]
        }
    },
    {
        "name": "manage_center",
        "description": (
            "Start, stop, restart or check the status of the Jarvis Center service. "
            "Also shows recent logs and health of API, PostgreSQL and Redis. "
            "Works whether the center is installed as a Windows service (JarvisCenter) "
            "or running as a standalone Python process."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": ["status", "start", "stop", "restart", "logs"],
                    "description": "Action to perform"
                },
                "lines": {
                    "type": "integer",
                    "description": "Number of log lines to show (only for action=logs, default 50)"
                }
            },
            "required": ["action"]
        }
    },
    {
        "name": "manage_solution_engine",
        "description": (
            "Enable or disable the Solution Driver (the engine that watches for critical problems, "
            "generates AI solutions and notifies configured webhooks). "
            "Use action='status' to check current state and webhook health. "
            "Use action='enable' or action='disable' to toggle. "
            "The engine only runs if it is enabled AND at least one webhook is configured and responding."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": ["status", "enable", "disable"],
                    "description": "Action to perform"
                }
            },
            "required": ["action"]
        }
    },
    {
        "name": "query_machine_profile",
        "description": (
            "Devolve o perfil aprendido de uma máquina: role (web server, DB, DC, file server...), "
            "ambiente (production/staging/dev), serviços críticos para o negócio, "
            "e impacto esperado de cada falha. Construído pelo MachineProfileEngine com base "
            "em snapshots, serviços, processos e reasoning histórico."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "host": {"type": "string", "description": "Filtro por host (parcial, opcional — omitir para todos)"}
            }
        }
    },
    {
        "name": "build_machine_profiles",
        "description": (
            "Constrói ou actualiza os perfis de máquina usando os dados históricos da DB. "
            "Analisa snapshots, serviços, processos, reasoning e alertas de cada host "
            "e usa AI para classificar: role, ambiente, serviços críticos, impacto de negócio. "
            "Demora ~1-2 min por host. Usa host='' para processar todos."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "host": {"type": "string", "description": "Host específico (parcial) ou '' para todos"}
            }
        }
    },
    {
        "name": "query_user_profiles",
        "description": (
            "Devolve perfis UEBA de utilizadores: padrão comportamental, score de risco, "
            "horários típicos de trabalho, aplicações primárias, actividade fora de horas, "
            "anomalias detectadas. Inclui contas de serviço e utilizadores humanos."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "host":     {"type": "string", "description": "Filtro por host (parcial, opcional)"},
                "username": {"type": "string", "description": "Filtro por username (parcial, opcional)"}
            }
        }
    },
    {
        "name": "query_ueba",
        "description": (
            "Devolve análises UEBA — anomalias comportamentais detectadas para utilizadores específicos. "
            "Inclui logins fora de horas, acessos a destinos suspeitos, escalada de privilégios, "
            "desvios do perfil normal."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "host":          {"type": "string",  "description": "Filtro por host (parcial, opcional)"},
                "username":      {"type": "string",  "description": "Filtro por username (parcial, opcional)"},
                "since_minutes": {"type": "integer", "description": "Janela temporal em minutos. Default: 10080 (7 dias)"}
            }
        }
    },
    {
        "name": "query_reasoning",
        "description": (
            "Devolve as últimas análises AI geradas pelo Jarvis para um host — "
            "diagnósticos detalhados com causa raiz, tendências, correlações e recomendações "
            "produzidas pelo reasoning engine em tempo real."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "host":  {"type": "string",  "description": "Filtro por host (parcial, opcional)"},
                "limit": {"type": "integer", "description": "Número de análises a devolver (max 10). Default: 5"}
            }
        }
    },
    {
        "name": "analyze_time_pattern",
        "description": (
            "Analyse historical events for a host grouped by hour-of-day and day-of-week to find recurring patterns. "
            "Use this to detect issues that repeat at predictable times (e.g. service crash every day at 16h, "
            "memory spike every Monday morning). Returns top recurring event types with hour/day breakdown."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "host":       {"type": "string",  "description": "Host key (partial match)"},
                "event_type": {"type": "string",  "description": "Filter to a specific event_type (optional)"},
                "days_back":  {"type": "integer", "description": "How many days of history to analyse (default 30)"}
            },
            "required": ["host"]
        }
    },
    {
        "name": "query_security_events",
        "description": (
            "Consulta eventos de segurança: logins suspeitos, discovery_change, network_throughput_spike, "
            "service_stopped em serviços críticos, privilege_escalation. "
            "USA ESTA FERRAMENTA quando o utilizador pergunta sobre segurança, intrusões, acessos suspeitos, "
            "anomalias de rede ou alterações de configuração. "
            "Inclui contexto UEBA e perfis de utilizador para distinguir utilizadores autorizados de suspeitos. "
            "NÃO usa para perguntas de performance (CPU, memória, disco)."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "host":          {"type": "string",  "description": "Filtro por host (parcial, opcional)"},
                "since_minutes": {"type": "integer", "description": "Janela temporal. Default: 1440 (24h)"},
                "include_ueba":  {"type": "boolean", "description": "Incluir análises UEBA de utilizadores. Default: true"}
            }
        }
    },
    {
        "name": "manage_authorized_users",
        "description": (
            "Gere a lista de utilizadores autorizados/confiáveis para o sistema UEBA. "
            "Utilizadores nesta lista não são sinalizados como suspeitos por actividade normal de administração. "
            "Usa action='list' para ver a lista actual, 'add' para adicionar, 'remove' para remover."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "action":   {"type": "string", "enum": ["list", "add", "remove"],
                             "description": "Acção a realizar"},
                "username": {"type": "string", "description": "Username a adicionar/remover (ex: YOURDOMAIN\\username)"},
                "reason":   {"type": "string", "description": "Razão/função do utilizador (opcional para add)"}
            },
            "required": ["action"]
        }
    },
]


def execute_tool(name: str, args: dict) -> tuple[str, str]:
    """Execute a tool. Returns (result_json, sql_summary)."""
    try:
        dispatch = {
            "query_problems":                    _query_problems,
            "query_events":                      _query_events,
            "query_agents":                      _query_agents,
            "query_metrics":                     _query_metrics,
            "query_alerts":                      _query_alerts,
            "get_config":                        _get_config,
            "query_instrumentation_coverage":    _query_instrumentation_coverage,
            "query_instrumentation_recommendations": _query_instrumentation_recommendations,
            "request_instrumentation":           _request_instrumentation,
            "agentless_run":                     _agentless_run,
            "analyze_time_pattern":              _analyze_time_pattern,
            "query_machine_profile":             _query_machine_profile,
            "build_machine_profiles":            _build_machine_profiles,
            "query_user_profiles":               _query_user_profiles,
            "query_ueba":                        _query_ueba,
            "query_reasoning":                   _query_reasoning,
            "query_security_events":             _query_security_events,
            "manage_authorized_users":           _manage_authorized_users,
            "manage_center":                      _manage_center,
            "manage_webhook":                    _manage_webhook,
            "manage_solution_engine":            _manage_solution_engine,
            "list_conversations":                _list_conversations,
            "get_conversation":                  _get_conversation,
        }
        fn = dispatch.get(name)
        if fn is None:
            return json.dumps({"error": f"Unknown tool: {name}"}), ""
        return fn(**args)
    except Exception as e:
        # Rollback para não deixar a transacção num estado abortado que bloqueia queries seguintes
        try:
            get_db().rollback()
        except Exception:
            pass
        return json.dumps({"error": str(e)}), ""


def _ts(row: dict, *keys):
    for k in keys:
        if row.get(k):
            row[k] = str(row[k])
    return row


def _query_problems(status="all", host=None, limit=10):
    conn = get_db()
    cur  = conn.cursor()
    where, params = [], []
    if status != "all":
        where.append("status = %s"); params.append(status)
    if host:
        where.append("host ILIKE %s"); params.append(f"%{host}%")
    w   = ("WHERE " + " AND ".join(where)) if where else ""
    sql = f"SELECT problem_id, host, title, severity, status, alert_count, opened_at, last_seen, duration_s FROM problems {w} ORDER BY opened_at DESC LIMIT %s"
    params.append(limit)
    cur.execute(sql, params)
    cols = [d[0] for d in cur.description]
    rows = [_ts(dict(zip(cols, r)), "opened_at", "last_seen") for r in cur.fetchall()]
    return json.dumps(rows, default=str), f"problems {w} LIMIT {limit}"


def _query_events(host=None, event_type=None, severity=None, since_minutes=60, limit=20):
    conn = get_db()
    cur  = conn.cursor()
    where  = [f"created_at >= NOW() - INTERVAL '{int(since_minutes)} minutes'"]
    params = []
    if host:        where.append("host ILIKE %s");       params.append(f"%{host}%")
    if event_type:  where.append("event_type = %s");     params.append(event_type)
    if severity:    where.append("severity = %s");       params.append(severity)
    w   = "WHERE " + " AND ".join(where)
    sql = f"SELECT host, event_type, severity, summary, created_at FROM events {w} ORDER BY created_at DESC LIMIT %s"
    params.append(limit)
    cur.execute(sql, params)
    cols = [d[0] for d in cur.description]
    rows = [_ts(dict(zip(cols, r)), "created_at") for r in cur.fetchall()]
    return json.dumps(rows, default=str), f"events (last {since_minutes}m) LIMIT {limit}"


def _query_agents(active_only=False):
    conn = get_db()
    cur  = conn.cursor()
    if active_only:
        sql = "SELECT host, TO_TIMESTAMP(MAX(snapshot_time)) AS last_seen FROM snapshots WHERE snapshot_time >= EXTRACT(EPOCH FROM NOW() - INTERVAL '5 minutes') GROUP BY host ORDER BY last_seen DESC"
    else:
        sql = "SELECT host, TO_TIMESTAMP(MAX(snapshot_time)) AS last_seen FROM snapshots GROUP BY host ORDER BY last_seen DESC"
    cur.execute(sql)
    cols = [d[0] for d in cur.description]
    rows = [_ts(dict(zip(cols, r)), "last_seen") for r in cur.fetchall()]
    return json.dumps(rows, default=str), sql


def _query_metrics(host, since_minutes=60):
    # snapshot_time é DOUBLE PRECISION (epoch Unix) — nunca usar comparação com timestamptz
    conn = get_db()
    cur  = conn.cursor()
    cur.execute(
        """
        SELECT snapshot_time, cpu_percent, memory_percent, disk_percent
          FROM snapshots
         WHERE host ILIKE %s
           AND snapshot_time >= EXTRACT(EPOCH FROM NOW() - INTERVAL %s)
         ORDER BY snapshot_time DESC
         LIMIT 60
        """,
        (f"%{host}%", f"{int(since_minutes)} minutes"),
    )
    cols = [d[0] for d in cur.description]
    rows = [dict(zip(cols, r)) for r in cur.fetchall()]
    return json.dumps(rows, default=str), f"snapshots WHERE host ILIKE '%{host}%' (last {since_minutes}m)"


def _query_alerts(host=None, severity=None, since_minutes=60, limit=20):
    conn = get_db()
    cur  = conn.cursor()
    where  = [f"created_at >= NOW() - INTERVAL '{int(since_minutes)} minutes'"]
    params = []
    if host:     where.append("host ILIKE %s");  params.append(f"%{host}%")
    if severity: where.append("severity = %s");  params.append(severity)
    w   = "WHERE " + " AND ".join(where)
    sql = f"SELECT host, title, severity, created_at FROM alerts {w} ORDER BY created_at DESC LIMIT %s"
    params.append(limit)
    cur.execute(sql, params)
    cols = [d[0] for d in cur.description]
    rows = [_ts(dict(zip(cols, r)), "created_at") for r in cur.fetchall()]
    return json.dumps(rows, default=str), f"alerts (last {since_minutes}m) LIMIT {limit}"


def _query_instrumentation_coverage(host, since_minutes=30):
    conn = get_db()
    cur  = conn.cursor()

    # Processos conhecidos do último snapshot
    cur.execute("""
        SELECT raw_json FROM snapshots
        WHERE host ILIKE %s ORDER BY snapshot_time DESC LIMIT 1
    """, [f"%{host}%"])
    row = cur.fetchone()
    processes = []
    if row and row[0]:
        import json as _json
        snap = _json.loads(row[0]) if isinstance(row[0], str) else row[0]
        processes = snap.get("processes") or []

    # Serviços que produziram traces recentemente
    cur.execute("""
        SELECT DISTINCT payload->>'service' AS service
        FROM traces
        WHERE host ILIKE %s
          AND recorded_at >= NOW() - INTERVAL '%s minutes'
          AND payload->>'service' IS NOT NULL
        LIMIT 50
    """, [f"%{host}%", int(since_minutes)])
    traced = {r[0] for r in cur.fetchall() if r[0]}

    # Cruzar
    proc_names = {(p.get("name") or "").lower().replace(".exe", "") for p in processes}
    instrumented   = sorted(traced & proc_names)
    not_instrumented = sorted(proc_names - traced - {""})

    result = {
        "instrumented_services": list(traced),
        "running_processes_not_traced": not_instrumented[:20],
        "coverage_pct": round(len(instrumented) / max(len(proc_names), 1) * 100, 1),
    }
    return json.dumps(result), f"traces + snapshots WHERE host ILIKE '%{host}%'"


def _query_instrumentation_recommendations(host=None, status="all"):
    conn = get_db()
    cur  = conn.cursor()
    try:
        where, params = [], []
        if host:
            where.append("host ILIKE %s"); params.append(f"%{host}%")
        if status != "all":
            where.append("status = %s"); params.append(status)
        w   = ("WHERE " + " AND ".join(where)) if where else ""
        sql = f"SELECT id, host, process_name, technology, priority, reason, source, status, created_at, applied_at FROM instrumentation_recommendations {w} ORDER BY created_at DESC LIMIT 30"
        cur.execute(sql, params)
        cols = [d[0] for d in cur.description]
        rows = [_ts(dict(zip(cols, r)), "created_at", "applied_at") for r in cur.fetchall()]
        return json.dumps(rows, default=str), sql
    except Exception as e:
        try: conn.rollback()
        except Exception: pass
        return json.dumps({"error": str(e)}), ""


def _request_instrumentation(host, process_name, reason, pid=None,
                              technology="python", priority="normal"):
    conn = get_db()
    cur  = conn.cursor()
    try:
        cur.execute("""
            INSERT INTO instrumentation_recommendations
                (host, pid, process_name, technology, priority, reason, source, status)
            VALUES (%s, %s, %s, %s, %s, %s, 'jarvis_chat', 'pending')
            RETURNING id
        """, (host, pid, process_name, technology, priority, reason))
        conn.commit()
        rec_id = cur.fetchone()[0]
        return json.dumps({"created": True, "id": rec_id, "message": f"Recomendação criada — o agente em '{host}' irá injectar '{process_name}' no próximo ciclo."}), ""
    except Exception as e:
        try: conn.rollback()
        except Exception: pass
        return json.dumps({"error": str(e)}), ""


def _get_config(category=None):
    conn = get_db()
    cur  = conn.cursor()
    try:
        if category:
            cur.execute("SELECT key, value, type, category, description FROM jarvis_config WHERE category = %s ORDER BY key", [category])
        else:
            cur.execute("SELECT key, value, type, category, description FROM jarvis_config ORDER BY category, key")
        cols = [d[0] for d in cur.description]
        rows = [dict(zip(cols, r)) for r in cur.fetchall()]
        return json.dumps(rows, default=str), "SELECT * FROM jarvis_config"
    except Exception as e:
        try: conn.rollback()
        except Exception: pass
        return json.dumps({"error": str(e)}), ""


# ── Solution Driver ───────────────────────────────────────────────────────────


def _agentless_run(machine: str, script: str, machine_type: str = "workstation", timeout_s: int = 60) -> tuple[str, str]:
    """
    Executa um script PowerShell numa máquina sem agente via WinRM.
    Executa um script PowerShell numa máquina remota via WinRM.
    """
    import config as _cfg
    center_url = _cfg.center_api_url() or os.getenv("JARVIS_CENTER_URL", "http://localhost:8080")
    api_key    = _cfg.center_api_key() or os.getenv("JARVIS_API_KEY", "")
    timeout_s  = max(10, min(int(timeout_s), 120))

    try:
        resp = _requests.post(
            f"{center_url}/agentless/execute",
            json={
                "machine":      machine,
                "script":       script,
                "machine_type": machine_type,
                "timeout_s":    timeout_s,
            },
            headers={"X-API-Key": api_key},
            timeout=timeout_s + 30,
        )
        resp.raise_for_status()
        data = resp.json()
        result = {
            "machine":   data.get("machine"),
            "exit_code": data.get("exit_code"),
            "stdout":    (data.get("stdout") or "").strip(),
            "stderr":    (data.get("stderr") or "").strip(),
            "ok":        data.get("ok", False),
        }
        label = f"agentless_run host={machine}"
        return json.dumps(result, ensure_ascii=False), label

    except _requests.exceptions.Timeout:
        return json.dumps({
            "machine":   machine,
            "exit_code": -2,
            "stdout":    "",
            "stderr":    f"WinRM não respondeu em {timeout_s + 30}s. Verificar se a máquina está online e acessível.",
            "ok":        False,
        }), f"agentless_run host={machine} TIMEOUT"
    except Exception as e:
        return json.dumps({"error": str(e), "machine": machine}), ""


_SVC_NAME    = "JarvisCenter"
_INSTALL_DIR = r"C:\JarvisCenter"
_DEV_DIR     = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "jarvis_center")
_LOG_STDOUT  = os.path.join(_INSTALL_DIR, "logs", "stdout.log")
_LOG_STDERR  = os.path.join(_INSTALL_DIR, "logs", "stderr.log")


def _run_cmd(args: list[str]) -> tuple[int, str, str]:
    """Corre um comando e devolve (returncode, stdout, stderr)."""
    try:
        r = __import__("subprocess").run(
            args, capture_output=True, text=True, timeout=15,
            creationflags=0x08000000,  # CREATE_NO_WINDOW
        )
        return r.returncode, r.stdout.strip(), r.stderr.strip()
    except Exception as e:
        return -1, "", str(e)


def _svc_state() -> str | None:
    """Devolve o estado do serviço Windows ou None se não existir."""
    rc, out, _ = _run_cmd(["sc", "query", _SVC_NAME])
    if rc != 0:
        return None
    for line in out.splitlines():
        if "STATE" in line:
            parts = line.split()
            # ex: "STATE              : 4  RUNNING"
            for i, p in enumerate(parts):
                if p in ("RUNNING", "STOPPED", "PAUSED", "START_PENDING", "STOP_PENDING"):
                    return p
    return "UNKNOWN"


def _api_health() -> tuple[bool, str]:
    import config as _cfg
    base = (_cfg.center_api_url() or f"http://localhost:{os.getenv('JARVIS_API_PORT', '8080')}").rstrip("/")
    try:
        resp = _requests.get(f"{base}/", timeout=3)
        return True, f"HTTP {resp.status_code}"
    except Exception as e:
        return False, str(e)


def _redis_health() -> tuple[bool, str]:
    import socket as _sock
    host = os.getenv("REDIS_HOST", "localhost")
    port = int(os.getenv("REDIS_PORT", "6379"))
    try:
        s = _sock.create_connection((host, port), timeout=2)
        s.close()
        return True, f"{host}:{port} OK"
    except Exception as e:
        return False, str(e)


def _db_health() -> tuple[bool, str]:
    try:
        cur = get_db().cursor()
        cur.execute("SELECT COUNT(*) FROM snapshots")
        count = cur.fetchone()[0]
        return True, f"OK ({count} snapshots)"
    except Exception as e:
        return False, str(e)


def _tail_file(path: str, n: int) -> list[str]:
    if not os.path.exists(path):
        return []
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return f.readlines()[-n:]
    except Exception:
        return []


def _manage_center(action: str, lines: int = 50) -> tuple[str, str]:
    svc = _svc_state()  # None = não instalado como serviço

    # ── STATUS ────────────────────────────────────────────────────────────────
    if action == "status":
        api_ok,   api_msg   = _api_health()
        redis_ok, redis_msg = _redis_health()
        db_ok,    db_msg    = _db_health()

        if svc is not None:
            center_running = svc == "RUNNING"
            center_info    = f"Serviço Windows ({_SVC_NAME}): {svc}"
        else:
            # Verificar processo python start_center.py
            rc, out, _ = _run_cmd(
                ["tasklist", "/FI", "IMAGENAME eq python.exe", "/FO", "CSV", "/NH"]
            )
            # Heurística: API a responder significa center a correr
            center_running = api_ok
            center_info    = "Processo standalone (sem serviço Windows)"

        return json.dumps({
            "center": {
                "running": center_running,
                "info":    center_info,
            },
            "api":   {"ok": api_ok,   "detail": api_msg},
            "redis": {"ok": redis_ok, "detail": redis_msg},
            "db":    {"ok": db_ok,    "detail": db_msg},
            "summary": (
                "ONLINE — todos os componentes a funcionar"
                if center_running and api_ok and redis_ok and db_ok
                else "DEGRADADO — verificar componentes em erro"
            ),
        }), "center status"

    # ── START ─────────────────────────────────────────────────────────────────
    if action == "start":
        if svc is not None:
            if svc == "RUNNING":
                return json.dumps({"message": f"Serviço {_SVC_NAME} já está a correr."}), ""
            rc, out, err = _run_cmd(["net", "start", _SVC_NAME])
            ok = rc == 0 or "already" in out.lower()
            return json.dumps({
                "started": ok,
                "message": f"net start {_SVC_NAME}: {'OK' if ok else err or out}",
            }), ""
        else:
            # Standalone: lança start_center.py em background
            center_dir = _INSTALL_DIR if os.path.isdir(_INSTALL_DIR) else _DEV_DIR
            script     = os.path.join(center_dir, "start_center.py")
            if not os.path.exists(script):
                return json.dumps({"error": f"start_center.py não encontrado em {center_dir}"}), ""
            import subprocess as _sp
            _sp.Popen(
                [sys.executable, script],
                cwd=center_dir,
                creationflags=_sp.CREATE_NEW_CONSOLE,
            )
            return json.dumps({
                "started": True,
                "message": f"Center iniciado como processo standalone em {center_dir}. Aguarda ~5s.",
            }), ""

    # ── STOP ──────────────────────────────────────────────────────────────────
    if action == "stop":
        if svc is not None:
            if svc == "STOPPED":
                return json.dumps({"message": f"Serviço {_SVC_NAME} já está parado."}), ""
            rc, out, err = _run_cmd(["net", "stop", _SVC_NAME])
            ok = rc == 0 or "already" in out.lower()
            return json.dumps({
                "stopped": ok,
                "message": f"net stop {_SVC_NAME}: {'OK' if ok else err or out}",
            }), ""
        else:
            # Standalone: matar processos python com start_center.py na linha de comando
            rc, out, err = _run_cmd([
                "wmic", "process", "where",
                "name='python.exe' and commandline like '%start_center%'",
                "call", "terminate",
            ])
            return json.dumps({
                "stopped": rc == 0,
                "message": "Processos start_center.py terminados." if rc == 0 else (err or out),
            }), ""

    # ── RESTART ───────────────────────────────────────────────────────────────
    if action == "restart":
        if svc is not None:
            _run_cmd(["net", "stop", _SVC_NAME])
            __import__("time").sleep(3)
            rc, out, err = _run_cmd(["net", "start", _SVC_NAME])
            ok = rc == 0
            return json.dumps({
                "restarted": ok,
                "message": f"net stop + net start {_SVC_NAME}: {'OK' if ok else err or out}",
            }), ""
        else:
            # stop + start standalone
            _run_cmd([
                "wmic", "process", "where",
                "name='python.exe' and commandline like '%start_center%'",
                "call", "terminate",
            ])
            __import__("time").sleep(2)
            center_dir = _INSTALL_DIR if os.path.isdir(_INSTALL_DIR) else _DEV_DIR
            script     = os.path.join(center_dir, "start_center.py")
            import subprocess as _sp
            _sp.Popen(
                [sys.executable, script],
                cwd=center_dir,
                creationflags=_sp.CREATE_NEW_CONSOLE,
            )
            return json.dumps({"restarted": True, "message": "Center reiniciado."}), ""

    # ── LOGS ──────────────────────────────────────────────────────────────────
    if action == "logs":
        lines = max(10, min(int(lines), 500))
        if os.path.exists(_LOG_STDOUT):
            tail = _tail_file(_LOG_STDOUT, lines)
            return json.dumps({
                "file":  _LOG_STDOUT,
                "lines": len(tail),
                "content": "".join(tail),
            }), ""
        # Tentar stderr se stdout não existir
        if os.path.exists(_LOG_STDERR):
            tail = _tail_file(_LOG_STDERR, lines)
            return json.dumps({
                "file":  _LOG_STDERR,
                "lines": len(tail),
                "content": "".join(tail),
            }), ""
        return json.dumps({
            "message": (
                f"Ficheiros de log não encontrados em {_INSTALL_DIR}\\logs\\. "
                "Se o center correu em modo standalone (terminal), os logs ficam no stdout do processo."
            )
        }), ""

    return json.dumps({"error": f"Acção desconhecida: {action}"}), ""


def _manage_solution_engine(action: str) -> tuple[str, str]:
    """Activa, desactiva ou mostra o estado do Solution Driver."""
    try:
        conn = get_db()
        cur = conn.cursor()

        if action == "status":
            cur.execute("SELECT value FROM jarvis_config WHERE key='solution_driver.enabled'")
            row     = cur.fetchone()
            enabled = (row[0] if row else "false").lower() == "true"

            cur.execute(
                "SELECT name, url, min_severity, active FROM notification_webhooks ORDER BY created_at DESC"
            )
            webhooks = [
                {"name": r[0], "url": r[1], "min_severity": r[2], "active": r[3]}
                for r in cur.fetchall()
            ]
            active_webhooks = [w for w in webhooks if w["active"]]
            return json.dumps({
                "enabled":         enabled,
                "webhooks_total":  len(webhooks),
                "webhooks_active": len(active_webhooks),
                "webhooks":        webhooks,
                "message": (
                    "Solution Driver ACTIVO" if enabled else "Solution Driver INACTIVO"
                ) + (
                    f" — {len(active_webhooks)} webhook(s) configurado(s)"
                    if active_webhooks else " — sem webhooks activos (use manage_webhook add)"
                ),
            }), "jarvis_config + notification_webhooks"

        if action in ("enable", "disable"):
            value = "true" if action == "enable" else "false"
            cur.execute(
                """
                INSERT INTO jarvis_config (key, value, type, category, description, updated_at)
                VALUES ('solution_driver.enabled', %s, 'bool', 'solution_driver',
                        'Activar Solution Driver', NOW())
                ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value, updated_at=NOW()
                """,
                (value,),
            )
            conn.commit()
            if action == "enable":
                cur.execute("SELECT COUNT(*) FROM notification_webhooks WHERE active=TRUE")
                wh_count = cur.fetchone()[0]
                msg = (
                    "Solution Driver ACTIVADO."
                    if wh_count > 0
                    else "Solution Driver ACTIVADO mas sem webhooks configurados — "
                         "use manage_webhook add <url> para receber notificações."
                )
            else:
                msg = "Solution Driver DESACTIVADO. Nenhuma notificação será enviada."
            return json.dumps({"action": action, "success": True, "message": msg}), ""

        return json.dumps({"error": f"Acção desconhecida: {action}"}), ""

    except Exception as e:
        try: get_db().rollback()
        except Exception: pass
        return json.dumps({"error": str(e)}), ""


def _manage_webhook(
    action: str,
    url: str = "",
    name: str = "",
    min_severity: str = "high",
    host_filter: str = "",
) -> tuple[str, str]:
    """Gere webhooks de notificação do Solution Driver."""
    try:
        conn = get_db()
        cur = conn.cursor()

        if action == "list":
            cur.execute(
                "SELECT id, name, url, min_severity, host_filter, active, created_at "
                "FROM notification_webhooks ORDER BY created_at DESC"
            )
            cols = [d[0] for d in cur.description]
            rows = [_ts(dict(zip(cols, r)), "created_at") for r in cur.fetchall()]
            return json.dumps({"webhooks": rows, "total": len(rows)}, default=str), \
                   "SELECT * FROM notification_webhooks"

        if not url:
            return json.dumps({"error": "url é obrigatório para esta acção"}), ""

        if action == "add":
            host_list = [h.strip() for h in host_filter.split(",") if h.strip()] or None
            cur.execute(
                """
                INSERT INTO notification_webhooks (name, url, min_severity, host_filter, active)
                VALUES (%s, %s, %s, %s, TRUE)
                ON CONFLICT DO NOTHING
                RETURNING id
                """,
                (name or url, url, min_severity, host_list),
            )
            conn.commit()
            row = cur.fetchone()
            if not row:
                return json.dumps({"added": False, "message": "URL já existe"}), ""

            # Teste imediato ao endpoint
            endpoint_ok   = False
            endpoint_msg  = ""
            try:
                resp = _requests.post(
                    url,
                    json={"type": "jarvis_health_check", "version": "1.0"},
                    timeout=5,
                )
                endpoint_ok  = True
                endpoint_msg = f"Endpoint respondeu com HTTP {resp.status_code}."
            except Exception as ex:
                endpoint_msg = f"Endpoint não respondeu: {ex}"

            return json.dumps({
                "added":          True,
                "id":             row[0],
                "url":            url,
                "min_severity":   min_severity,
                "endpoint_ok":    endpoint_ok,
                "endpoint_check": endpoint_msg,
                "message": (
                    f"Webhook registado. {endpoint_msg} "
                    f"O Jarvis enviará notificações para '{url}' "
                    f"quando detectar problemas de severidade >= {min_severity}. "
                    "O payload inclui um callback_url para o analista responder."
                ) if endpoint_ok else (
                    f"Webhook registado mas o endpoint não está acessível: {endpoint_msg} "
                    "Verifica a URL e garante que o servidor está a aceitar POST. "
                    "O Solution Driver só dispara se o endpoint responder no momento do alerta."
                ),
            }), ""

        if action in ("enable", "disable"):
            active = action == "enable"
            cur.execute(
                "UPDATE notification_webhooks SET active=%s WHERE url=%s RETURNING id",
                (active, url),
            )
            conn.commit()
            row = cur.fetchone()
            if row:
                return json.dumps({"updated": True, "url": url, "active": active}), ""
            return json.dumps({"error": "Webhook não encontrado"}), ""

        if action == "remove":
            cur.execute(
                "DELETE FROM notification_webhooks WHERE url=%s RETURNING id", (url,)
            )
            conn.commit()
            row = cur.fetchone()
            if row:
                return json.dumps({"removed": True, "url": url}), ""
            return json.dumps({"error": "Webhook não encontrado"}), ""

        return json.dumps({"error": f"Acção desconhecida: {action}"}), ""

    except Exception as e:
        try: get_db().rollback()
        except Exception: pass
        return json.dumps({"error": str(e)}), ""


def _list_conversations(
    status: str = "all",
    host: str = "",
    limit: int = 10,
) -> tuple[str, str]:
    """Lista conversas do Solution Driver."""
    try:
        conn = get_db()
        cur  = conn.cursor()
        where  = []
        params = []

        if status != "all":
            where.append("status = %s")
            params.append(status)
        else:
            # Por omissão: exclui expiradas e resolvidas há mais de 1h
            where.append("(status NOT IN ('expired','resolved') OR updated_at > NOW() - INTERVAL '1 hour')")

        if host:
            where.append("host ILIKE %s")
            params.append(f"%{host}%")

        w   = ("WHERE " + " AND ".join(where)) if where else ""
        sql = (
            f"SELECT id, problem_id, host, status, risk_level, solution_summary, "
            f"created_at, updated_at, expires_at "
            f"FROM conversations {w} "
            f"ORDER BY created_at DESC LIMIT %s"
        )
        params.append(limit)
        cur.execute(sql, params)
        cols = [d[0] for d in cur.description]
        rows = [
            _ts(dict(zip(cols, r)), "created_at", "updated_at", "expires_at")
            for r in cur.fetchall()
        ]
        # Contar mensagens por conversa
        for row in rows:
            cur.execute(
                "SELECT COUNT(*) FROM conversation_messages WHERE conv_id=%s",
                (row["id"],)
            )
            row["message_count"] = cur.fetchone()[0]

        conn.commit()
        return json.dumps({"conversations": rows, "total": len(rows)}, default=str), \
               f"conversations {w} LIMIT {limit}"
    except Exception as e:
        try: get_db().rollback()
        except Exception: pass
        return json.dumps({"error": str(e)}), ""


def _get_conversation(conversation_id: str) -> tuple[str, str]:
    """Devolve conversa completa com histórico de mensagens."""
    try:
        conn = get_db()
        cur = conn.cursor()

        cur.execute(
            "SELECT id, problem_id, host, status, risk_level, solution_summary, "
            "proposed_script, created_at, updated_at, expires_at "
            "FROM conversations WHERE id=%s",
            (conversation_id,)
        )
        row = cur.fetchone()
        if not row:
            conn.commit()
            return json.dumps({"error": "Conversa não encontrada"}), ""

        cols = [d[0] for d in cur.description]
        conv = _ts(dict(zip(cols, row)), "created_at", "updated_at", "expires_at")

        cur.execute(
            "SELECT role, content, created_at FROM conversation_messages "
            "WHERE conv_id=%s ORDER BY created_at ASC",
            (conversation_id,)
        )
        msg_cols = [d[0] for d in cur.description]
        messages = [
            _ts(dict(zip(msg_cols, m)), "created_at")
            for m in cur.fetchall()
        ]

        conn.commit()
        return json.dumps({
            "conversation": conv,
            "messages":     messages,
            "message_count": len(messages),
        }, default=str), f"conversations + messages WHERE id={conversation_id}"
    except Exception as e:
        try: get_db().rollback()
        except Exception: pass
        return json.dumps({"error": str(e)}), ""


def _analyze_time_pattern(host: str, event_type: str | None = None, days_back: int = 30) -> tuple[str, str]:
    """
    Agrupa eventos históricos por hora-do-dia e dia-da-semana para detectar padrões recorrentes.
    Retorna os top padrões com contagem de ocorrências.
    """
    conn = get_db()
    cur  = conn.cursor()
    try:
        params: list = [f"%{host}%", int(days_back)]
        type_filter  = ""
        if event_type:
            type_filter = "AND event_type = %s"
            params.append(event_type)

        cur.execute(
            f"""
            SELECT
                event_type,
                EXTRACT(HOUR  FROM created_at)::INT  AS hour_of_day,
                EXTRACT(DOW   FROM created_at)::INT  AS day_of_week,
                COUNT(*)                             AS occurrences
            FROM events
            WHERE host ILIKE %s
              AND created_at > NOW() - INTERVAL '%s days'
              {type_filter}
            GROUP BY event_type, hour_of_day, day_of_week
            HAVING COUNT(*) >= 2
            ORDER BY occurrences DESC
            LIMIT 40
            """,
            params,
        )
        cols = [d[0] for d in cur.description]
        rows = [dict(zip(cols, r)) for r in cur.fetchall()]

        # Enriquecer com nome do dia da semana
        dow_names = {0: "Sunday", 1: "Monday", 2: "Tuesday", 3: "Wednesday",
                     4: "Thursday", 5: "Friday", 6: "Saturday"}
        for r in rows:
            r["day_name"] = dow_names.get(r.get("day_of_week", -1), "?")

        summary = {
            "host":     host,
            "days_analysed": days_back,
            "patterns": rows,
            "total_patterns_found": len(rows),
        }
        return json.dumps(summary, default=str), f"time_pattern host ILIKE '%{host}%' last {days_back}d"
    except Exception as e:
        try: conn.rollback()
        except Exception: pass
        return json.dumps({"error": str(e)}), ""


def _query_machine_profile(host: str = "") -> tuple[str, str]:
    """Devolve o perfil aprendido de uma máquina: role, ambiente, serviços críticos."""
    conn = get_db()
    cur  = conn.cursor()
    try:
        where  = ["1=1"]
        params = []
        if host:
            where.append("sp.host ILIKE %s"); params.append(f"%{host}%")
        cur.execute(
            f"SELECT host, profile, setup_at, updated_at FROM server_profiles sp WHERE {' AND '.join(where)} ORDER BY updated_at DESC LIMIT 20",
            params,
        )
        cols = [d[0] for d in cur.description]
        rows = [_ts(dict(zip(cols, r)), "setup_at", "updated_at") for r in cur.fetchall()]
        if not rows:
            return json.dumps({"message": "Sem perfis de máquina gerados ainda. Use build_machine_profiles para construir.", "count": 0}), ""
        return json.dumps({"profiles": rows, "count": len(rows)}, default=str), "server_profiles"
    except Exception as e:
        try: conn.rollback()
        except Exception: pass
        return json.dumps({"error": str(e)}), ""


def _query_user_profiles(host: str = "", username: str = "") -> tuple[str, str]:
    """Devolve perfis UEBA de utilizadores — padrões comportamentais, risco, horários, apps."""
    conn = get_db()
    cur  = conn.cursor()
    try:
        where, params = [], []
        if host:     where.append("host ILIKE %s");     params.append(f"%{host}%")
        if username: where.append("username ILIKE %s"); params.append(f"%{username}%")
        w = ("WHERE " + " AND ".join(where)) if where else ""
        cur.execute(
            f"""SELECT host, username, is_human, risk_score, risk_level, risk_delta,
                       work_type, primary_apps, typical_hours, active_days,
                       after_hours_activity, weekend_activity, privilege_abuse_detected,
                       behavioral_anomalies, summary, created_at
                FROM user_profiles {w} ORDER BY risk_score DESC LIMIT 30""",
            params,
        )
        cols = [d[0] for d in cur.description]
        rows = [_ts(dict(zip(cols, r)), "created_at") for r in cur.fetchall()]
        return json.dumps({"user_profiles": rows, "count": len(rows)}, default=str), f"user_profiles {w}"
    except Exception as e:
        try: conn.rollback()
        except Exception: pass
        return json.dumps({"error": str(e)}), ""


def _query_ueba(host: str = "", username: str = "", since_minutes: int = 10080) -> tuple[str, str]:
    """Devolve análises UEBA — anomalias comportamentais detectadas por utilizador."""
    conn = get_db()
    cur  = conn.cursor()
    try:
        where  = [f"analyzed_at >= NOW() - INTERVAL '{int(since_minutes)} minutes'"]
        params = []
        if host:     where.append("host ILIKE %s");     params.append(f"%{host}%")
        if username: where.append("username ILIKE %s"); params.append(f"%{username}%")
        w = "WHERE " + " AND ".join(where)
        cur.execute(
            f"""SELECT host, username, analysis_type, compliance_score, verdict,
                       summary, anomalies, events_analyzed, analyzed_at
                FROM ueba_analyses {w} ORDER BY analyzed_at DESC LIMIT 30""",
            params
        )
        cols = [d[0] for d in cur.description]
        rows = [_ts(dict(zip(cols, r)), "analyzed_at") for r in cur.fetchall()]
        return json.dumps({"ueba_analyses": rows, "count": len(rows)}, default=str), f"ueba_analyses {w}"
    except Exception as e:
        try: conn.rollback()
        except Exception: pass
        return json.dumps({"error": str(e)}), ""


def _query_reasoning(host: str = "", limit: int = 5) -> tuple[str, str]:
    """Devolve as últimas análises AI (reasoning) geradas pelo Jarvis para um host."""
    conn = get_db()
    cur  = conn.cursor()
    try:
        where, params = [], []
        if host: where.append("host ILIKE %s"); params.append(f"%{host}%")
        w = ("WHERE " + " AND ".join(where)) if where else ""
        params.append(min(int(limit), 10))
        cur.execute(
            f"SELECT host, summary, details, created_at FROM reasoning {w} ORDER BY created_at DESC LIMIT %s",
            params,
        )
        cols = [d[0] for d in cur.description]
        rows = [_ts(dict(zip(cols, r)), "created_at") for r in cur.fetchall()]
        return json.dumps({"reasoning": rows, "count": len(rows)}, default=str), f"reasoning {w}"
    except Exception as e:
        try: conn.rollback()
        except Exception: pass
        return json.dumps({"error": str(e)}), ""


def _query_security_events(host: str = "", since_minutes: int = 1440, include_ueba: bool = True) -> tuple[str, str]:
    """
    Investigação de segurança contextual: para cada utilizador/host envolvido, enriquece
    com o perfil comportamental guardado (horários típicos, função, apps) e o perfil da
    máquina (serviços críticos, papel, impacto). Sem listas estáticas — todo o contexto
    vem dos dados recolhidos pelo Jarvis.
    """
    conn = get_db()
    cur  = conn.cursor()
    try:
        # 1. Eventos de segurança recentes
        security_types = (
            "discovery_change", "network_throughput_spike", "service_stopped",
            "login_failed", "privilege_escalation", "unauthorized_access",
            "new_listening_port", "process_anomaly", "lateral_movement",
        )
        placeholders = ",".join(["%s"] * len(security_types))
        ev_where = [
            f"created_at >= NOW() - INTERVAL '{int(since_minutes)} minutes'",
            f"event_type IN ({placeholders})",
        ]
        ev_params: list = list(security_types)
        if host:
            ev_where.append("host ILIKE %s")
            ev_params.append(f"%{host}%")
        cur.execute(
            f"SELECT host, event_type, severity, summary, payload, created_at "
            f"FROM events WHERE {' AND '.join(ev_where)} ORDER BY created_at DESC LIMIT 50",
            ev_params,
        )
        cols = [d[0] for d in cur.description]
        events = [_ts(dict(zip(cols, r)), "created_at") for r in cur.fetchall()]

        # Hosts únicos envolvidos
        affected_hosts = list({e["host"] for e in events})

        # 2. UEBA — análises suspeitas/high_risk (janela alargada: 7 dias)
        ueba_entries = []
        if include_ueba:
            ueba_where = [
                f"analyzed_at >= NOW() - INTERVAL '{min(int(since_minutes) * 7, 10080)} minutes'",
                "verdict IN ('suspicious','high_risk')",
            ]
            ueba_params: list = []
            if host:
                ueba_where.append("host ILIKE %s")
                ueba_params.append(f"%{host}%")
            cur.execute(
                f"""SELECT host, username, compliance_score, verdict,
                           summary, anomalies, events_analyzed, analyzed_at
                    FROM ueba_analyses
                    WHERE {' AND '.join(ueba_where)}
                    ORDER BY compliance_score ASC LIMIT 25""",
                ueba_params,
            )
            cols = [d[0] for d in cur.description]
            ueba_entries = [_ts(dict(zip(cols, r)), "analyzed_at") for r in cur.fetchall()]
            for e in ueba_entries:
                if e["host"] not in affected_hosts:
                    affected_hosts.append(e["host"])

        # Utilizadores únicos presentes nas análises UEBA
        unique_users = list({e["username"] for e in ueba_entries if e.get("username")})

        # 3. Enriquecimento: perfil comportamental de cada utilizador
        user_context: dict = {}
        if unique_users:
            user_placeholders = ",".join(["%s"] * len(unique_users))
            cur.execute(
                f"""SELECT host, username, is_human, risk_score, risk_level, risk_delta,
                           work_type, primary_apps, typical_hours, active_days,
                           after_hours_activity, weekend_activity,
                           privilege_abuse_detected, behavioral_anomalies, summary
                    FROM user_profiles
                    WHERE username IN ({user_placeholders})
                    ORDER BY risk_score DESC""",
                unique_users,
            )
            cols = [d[0] for d in cur.description]
            for r in cur.fetchall():
                row_d = dict(zip(cols, r))
                key = (row_d["username"], row_d["host"])
                user_context[key] = row_d
                # Guardar também só por username para lookup cruzado
                if row_d["username"] not in user_context:
                    user_context[row_d["username"]] = row_d

        # Injectar contexto do utilizador em cada entrada UEBA
        for entry in ueba_entries:
            uname = entry.get("username", "")
            hname = entry.get("host", "")
            profile = user_context.get((uname, hname)) or user_context.get(uname)
            if profile:
                entry["user_profile"] = {
                    "is_human":            profile.get("is_human"),
                    "work_type":           profile.get("work_type"),
                    "typical_hours":       profile.get("typical_hours"),
                    "active_days":         profile.get("active_days"),
                    "after_hours_activity":profile.get("after_hours_activity"),
                    "weekend_activity":    profile.get("weekend_activity"),
                    "risk_score":          profile.get("risk_score"),
                    "risk_level":          profile.get("risk_level"),
                    "risk_delta":          profile.get("risk_delta"),
                    "primary_apps":        profile.get("primary_apps"),
                    "privilege_abuse":     profile.get("privilege_abuse_detected"),
                    "behavioral_anomalies":profile.get("behavioral_anomalies"),
                    "profile_summary":     profile.get("summary"),
                }
            else:
                entry["user_profile"] = None  # sem dados históricos sobre este utilizador

        # 4. Enriquecimento: perfil de cada host afectado (serviços críticos, papel, impacto)
        machine_context: dict = {}
        if affected_hosts:
            host_placeholders = ",".join(["%s"] * len(affected_hosts))
            # host na DB pode ter sufixo ::uuid — usar ILIKE para cada host
            for ah in affected_hosts:
                ah_base = ah.split("::")[0]
                cur.execute(
                    "SELECT host, profile FROM server_profiles WHERE host ILIKE %s LIMIT 1",
                    (f"%{ah_base}%",),
                )
                row = cur.fetchone()
                if row:
                    prof = row[1] if isinstance(row[1], dict) else json.loads(row[1])
                    machine_context[ah] = {
                        "role":              prof.get("role"),
                        "env":               prof.get("env"),
                        "business_impact":   prof.get("business_impact"),
                        "critical_services": prof.get("critical_services", []),
                        "important_services":prof.get("important_services", []),
                        "tech_stack":        prof.get("tech_stack", []),
                        "risk_flags":        prof.get("risk_flags", []),
                        "role_detail":       prof.get("role_detail"),
                    }

        # 5. Problemas abertos nos hosts afectados
        open_problems = []
        if affected_hosts:
            for ah in affected_hosts:
                ah_base = ah.split("::")[0]
                cur.execute(
                    """SELECT problem_id, host, title, severity, alert_count, opened_at
                       FROM problems
                       WHERE host ILIKE %s AND status='open'
                       ORDER BY alert_count DESC LIMIT 3""",
                    (f"%{ah_base}%",),
                )
                cols = [d[0] for d in cur.description]
                for r in cur.fetchall():
                    open_problems.append(_ts(dict(zip(cols, r)), "opened_at"))

        return json.dumps({
            "security_events": events,
            "ueba_findings":   ueba_entries,
            "machine_profiles": machine_context,
            "open_problems":   open_problems,
            "summary": {
                "total_security_events": len(events),
                "ueba_suspicious_users": len({e["username"] for e in ueba_entries}),
                "affected_hosts":        len(affected_hosts),
                "hosts_with_profile":    len(machine_context),
                "open_problems":         len(open_problems),
            },
            "investigation_guide": (
                "Para cada utilizador em ueba_findings: consulta user_profile (típico vs actual). "
                "Para cada host: consulta machine_profiles (serviços críticos em risco?). "
                "Para cada open_problem: está relacionado com este utilizador/evento? "
                "Contas de sistema Windows (DWM-N, UMFD-N, Font Driver Host, NT AUTHORITY) "
                "têm comportamento de logon/logoff curto por design — verificar com agentless_run "
                "antes de escalar. Utilizadores sem user_profile são desconhecidos pelo Jarvis — "
                "investigar com agentless_run quem são e o que estavam a fazer."
            ),
        }, default=str), f"security_events + ueba + user_profiles + machine_profiles (last {since_minutes}m)"
    except Exception as e:
        try: conn.rollback()
        except Exception: pass
        return json.dumps({"error": str(e)}), ""


def _manage_authorized_users(action: str, username: str = "", reason: str = "") -> tuple[str, str]:
    """Gere a lista de utilizadores autorizados para o sistema UEBA."""
    conn = get_db()
    cur  = conn.cursor()
    try:
        cur.execute("SELECT value FROM jarvis_config WHERE key='ueba.authorized_users'")
        row = cur.fetchone()
        current: list = []
        if row and row[0]:
            try:
                current = json.loads(row[0]) if row[0].startswith("[") else [u.strip() for u in row[0].split(",") if u.strip()]
            except Exception:
                current = []

        if action == "list":
            return json.dumps({
                "authorized_users": current,
                "count": len(current),
                "message": (
                    f"{len(current)} utilizador(es) autorizado(s) configurado(s). "
                    "O UEBA sinaliza estes utilizadores com contexto 'autorizado' em vez de alarme directo."
                    if current else
                    "Nenhum utilizador autorizado configurado ainda. "
                    "Usa manage_authorized_users action='add' username='DOMINIO\\\\utilizador'."
                ),
            }), "jarvis_config ueba.authorized_users"

        if not username:
            return json.dumps({"error": "username é obrigatório para add/remove"}), ""

        if action == "add":
            if username not in current:
                current.append(username)
            cur.execute(
                """INSERT INTO jarvis_config (key, value, type, category, description, updated_at)
                   VALUES ('ueba.authorized_users', %s, 'json', 'ueba', 'Utilizadores autorizados (sem alerta UEBA)', NOW())
                   ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value, updated_at=NOW()""",
                (json.dumps(current),),
            )
            conn.commit()
            return json.dumps({
                "added": username,
                "authorized_users": current,
                "message": f"'{username}' adicionado à lista de utilizadores autorizados. O UEBA não vai escalar alertas deste utilizador sem evidência adicional.",
            }), ""

        if action == "remove":
            before = len(current)
            current = [u for u in current if u != username]
            cur.execute(
                """INSERT INTO jarvis_config (key, value, type, category, description, updated_at)
                   VALUES ('ueba.authorized_users', %s, 'json', 'ueba', 'Utilizadores autorizados (sem alerta UEBA)', NOW())
                   ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value, updated_at=NOW()""",
                (json.dumps(current),),
            )
            conn.commit()
            removed = before != len(current)
            return json.dumps({
                "removed": removed,
                "authorized_users": current,
                "message": f"'{username}' {'removido da' if removed else 'não encontrado na'} lista de utilizadores autorizados.",
            }), ""

        return json.dumps({"error": f"Acção desconhecida: {action}"}), ""
    except Exception as e:
        try: conn.rollback()
        except Exception: pass
        return json.dumps({"error": str(e)}), ""


def _build_machine_profiles(host: str = "") -> tuple[str, str]:
    """Dispara a construção/actualização de perfis de máquina com base nos dados existentes na DB."""
    import subprocess, sys, os
    script = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
        "jarvis_center", "engines", "machine_profile_engine.py"
    )
    if not os.path.exists(script):
        return json.dumps({"error": f"MachineProfileEngine não encontrado em {script}"}), ""
    try:
        args = [sys.executable, script]
        if host:
            args += ["--host", host]
        r = subprocess.run(args, capture_output=True, text=True, timeout=120,
                           cwd=os.path.dirname(script))
        return json.dumps({
            "launched": True,
            "stdout": r.stdout[-2000:] if r.stdout else "",
            "stderr": r.stderr[-500:]  if r.stderr else "",
            "returncode": r.returncode,
        }), "machine_profile_engine"
    except Exception as e:
        return json.dumps({"error": str(e)}), ""
